name: MyfirstGithubAction button

on:
  push:
    branches:
      - dev

jobs:
  deploy-to-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to AWS Lambda
        uses: softprops/action-aws-lambda@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ AWS_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ AWS_secret_key }}
          AWS_REGION: 'us-east-1'
          FUNCTION_NAME: 'myFirstlamba'
          HANDLER: './app.js'
          ZIP: '.'  